config/routes.rb
Rails.application.routes.draw do
  root :to => 'bukus#index'
  resources :bukus
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/buku.rb
class Buku
  include Mongoid::Document
  field :penulis, type: String
  field :judul, type: String
  field :kota, type: String
  field :penerbit, type: String
  field :tahun, type: Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bukus_controller.rb
class BukusController < ApplicationController
  before_action :set_buku, only: [:show, :edit, :update, :destroy]

  # GET /bukus
  # GET /bukus.json
  def index
    @bukus = Buku.all
  end

  # GET /bukus/1
  # GET /bukus/1.json
  def show
  end

  # GET /bukus/new
  def new
    @buku = Buku.new
  end

  # GET /bukus/1/edit
  def edit
  end

  # POST /bukus
  # POST /bukus.json
  def create
    @buku = Buku.new(buku_params)

    respond_to do |format|
      if @buku.save
        format.html { redirect_to @buku, notice: 'Buku was successfully created.' }
        format.json { render :show, status: :created, location: @buku }
      else
        format.html { render :new }
        format.json { render json: @buku.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bukus/1
  # PATCH/PUT /bukus/1.json
  def update
    respond_to do |format|
      if @buku.update(buku_params)
        format.html { redirect_to @buku, notice: 'Buku was successfully updated.' }
        format.json { render :show, status: :ok, location: @buku }
      else
        format.html { render :edit }
        format.json { render json: @buku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bukus/1
  # DELETE /bukus/1.json
  def destroy
    @buku.destroy
    respond_to do |format|
      format.html { redirect_to bukus_url, notice: 'Buku was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buku
      @buku = Buku.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buku_params
      params.require(:buku).permit(:penulis, :judul, :kota, :penerbit, :tahun)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bukus_helper.rb
module BukusHelper
end

app/views/bukus/_form.html.erb
<%= form_with(model: buku, local: true) do |form| %>
  <% if buku.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buku.errors.count, "error") %> prohibited this buku from being saved:</h2>

      <ul>
        <% buku.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :penulis %>
    <%= form.text_field :penulis %>
  </div>

  <div class="field">
    <%= form.label :judul %>
    <%= form.text_field :judul %>
  </div>

  <div class="field">
    <%= form.label :kota %>
    <%= form.text_field :kota %>
  </div>

  <div class="field">
    <%= form.label :penerbit %>
    <%= form.text_field :penerbit %>
  </div>

  <div class="field">
    <%= form.label :tahun %>
    <%= form.number_field :tahun %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bukus/edit.html.erb
<h1>Editing Buku</h1>

<%= render 'form', buku: @buku %>

<%= link_to 'Show', @buku %> |
<%= link_to 'Back', bukus_path %>

app/views/bukus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bukus</h1>

<table>
  <thead>
    <tr>
      <th>Penulis</th>
      <th>Judul</th>
      <th>Kota</th>
      <th>Penerbit</th>
      <th>Tahun</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bukus.each do |buku| %>
      <tr>
        <td><%= buku.penulis %></td>
        <td><%= buku.judul %></td>
        <td><%= buku.kota %></td>
        <td><%= buku.penerbit %></td>
        <td><%= buku.tahun %></td>
        <td><%= link_to 'Show', buku %></td>
        <td><%= link_to 'Edit', edit_buku_path(buku) %></td>
        <td><%= link_to 'Destroy', buku, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buku', new_buku_path %>

app/views/bukus/new.html.erb
<h1>New Buku</h1>

<%= render 'form', buku: @buku %>

<%= link_to 'Back', bukus_path %>

app/views/bukus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Penulis:</strong>
  <%= @buku.penulis %>
</p>

<p>
  <strong>Judul:</strong>
  <%= @buku.judul %>
</p>

<p>
  <strong>Kota:</strong>
  <%= @buku.kota %>
</p>

<p>
  <strong>Penerbit:</strong>
  <%= @buku.penerbit %>
</p>

<p>
  <strong>Tahun:</strong>
  <%= @buku.tahun %>
</p>

<%= link_to 'Edit', edit_buku_path(@buku) %> |
<%= link_to 'Back', bukus_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRailsCrudMongodbWithScaffold</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>